main: tk.redtech.unityMC.UnityMC
version: 1.0
name: Unity-MC

commands:
  gold:
    description: Add, set, or take away gold coins.
  store:
    description: Opens the server premium store.
  confirm:
    description: Confirms a purchase.
  inject:
    description: Not implemented.

